/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-dynatrace-api/apis/application/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeErrorRuleses implements ErrorRulesInterface
type FakeErrorRuleses struct {
	Fake *FakeApplicationV1alpha1
	ns   string
}

var errorrulesesResource = schema.GroupVersionResource{Group: "application.dynatrace.kubeform.com", Version: "v1alpha1", Resource: "errorruleses"}

var errorrulesesKind = schema.GroupVersionKind{Group: "application.dynatrace.kubeform.com", Version: "v1alpha1", Kind: "ErrorRules"}

// Get takes name of the errorRules, and returns the corresponding errorRules object, and an error if there is any.
func (c *FakeErrorRuleses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ErrorRules, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(errorrulesesResource, c.ns, name), &v1alpha1.ErrorRules{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ErrorRules), err
}

// List takes label and field selectors, and returns the list of ErrorRuleses that match those selectors.
func (c *FakeErrorRuleses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ErrorRulesList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(errorrulesesResource, errorrulesesKind, c.ns, opts), &v1alpha1.ErrorRulesList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ErrorRulesList{ListMeta: obj.(*v1alpha1.ErrorRulesList).ListMeta}
	for _, item := range obj.(*v1alpha1.ErrorRulesList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested errorRuleses.
func (c *FakeErrorRuleses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(errorrulesesResource, c.ns, opts))

}

// Create takes the representation of a errorRules and creates it.  Returns the server's representation of the errorRules, and an error, if there is any.
func (c *FakeErrorRuleses) Create(ctx context.Context, errorRules *v1alpha1.ErrorRules, opts v1.CreateOptions) (result *v1alpha1.ErrorRules, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(errorrulesesResource, c.ns, errorRules), &v1alpha1.ErrorRules{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ErrorRules), err
}

// Update takes the representation of a errorRules and updates it. Returns the server's representation of the errorRules, and an error, if there is any.
func (c *FakeErrorRuleses) Update(ctx context.Context, errorRules *v1alpha1.ErrorRules, opts v1.UpdateOptions) (result *v1alpha1.ErrorRules, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(errorrulesesResource, c.ns, errorRules), &v1alpha1.ErrorRules{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ErrorRules), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeErrorRuleses) UpdateStatus(ctx context.Context, errorRules *v1alpha1.ErrorRules, opts v1.UpdateOptions) (*v1alpha1.ErrorRules, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(errorrulesesResource, "status", c.ns, errorRules), &v1alpha1.ErrorRules{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ErrorRules), err
}

// Delete takes name of the errorRules and deletes it. Returns an error if one occurs.
func (c *FakeErrorRuleses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(errorrulesesResource, c.ns, name), &v1alpha1.ErrorRules{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeErrorRuleses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(errorrulesesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ErrorRulesList{})
	return err
}

// Patch applies the patch and returns the patched errorRules.
func (c *FakeErrorRuleses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ErrorRules, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(errorrulesesResource, c.ns, name, pt, data, subresources...), &v1alpha1.ErrorRules{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ErrorRules), err
}
