/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-dynatrace-api/apis/application/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDataPrivacies implements DataPrivacyInterface
type FakeDataPrivacies struct {
	Fake *FakeApplicationV1alpha1
	ns   string
}

var dataprivaciesResource = schema.GroupVersionResource{Group: "application.dynatrace.kubeform.com", Version: "v1alpha1", Resource: "dataprivacies"}

var dataprivaciesKind = schema.GroupVersionKind{Group: "application.dynatrace.kubeform.com", Version: "v1alpha1", Kind: "DataPrivacy"}

// Get takes name of the dataPrivacy, and returns the corresponding dataPrivacy object, and an error if there is any.
func (c *FakeDataPrivacies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DataPrivacy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(dataprivaciesResource, c.ns, name), &v1alpha1.DataPrivacy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DataPrivacy), err
}

// List takes label and field selectors, and returns the list of DataPrivacies that match those selectors.
func (c *FakeDataPrivacies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DataPrivacyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(dataprivaciesResource, dataprivaciesKind, c.ns, opts), &v1alpha1.DataPrivacyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DataPrivacyList{ListMeta: obj.(*v1alpha1.DataPrivacyList).ListMeta}
	for _, item := range obj.(*v1alpha1.DataPrivacyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dataPrivacies.
func (c *FakeDataPrivacies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(dataprivaciesResource, c.ns, opts))

}

// Create takes the representation of a dataPrivacy and creates it.  Returns the server's representation of the dataPrivacy, and an error, if there is any.
func (c *FakeDataPrivacies) Create(ctx context.Context, dataPrivacy *v1alpha1.DataPrivacy, opts v1.CreateOptions) (result *v1alpha1.DataPrivacy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(dataprivaciesResource, c.ns, dataPrivacy), &v1alpha1.DataPrivacy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DataPrivacy), err
}

// Update takes the representation of a dataPrivacy and updates it. Returns the server's representation of the dataPrivacy, and an error, if there is any.
func (c *FakeDataPrivacies) Update(ctx context.Context, dataPrivacy *v1alpha1.DataPrivacy, opts v1.UpdateOptions) (result *v1alpha1.DataPrivacy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(dataprivaciesResource, c.ns, dataPrivacy), &v1alpha1.DataPrivacy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DataPrivacy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDataPrivacies) UpdateStatus(ctx context.Context, dataPrivacy *v1alpha1.DataPrivacy, opts v1.UpdateOptions) (*v1alpha1.DataPrivacy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(dataprivaciesResource, "status", c.ns, dataPrivacy), &v1alpha1.DataPrivacy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DataPrivacy), err
}

// Delete takes name of the dataPrivacy and deletes it. Returns an error if one occurs.
func (c *FakeDataPrivacies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(dataprivaciesResource, c.ns, name), &v1alpha1.DataPrivacy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDataPrivacies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(dataprivaciesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.DataPrivacyList{})
	return err
}

// Patch applies the patch and returns the patched dataPrivacy.
func (c *FakeDataPrivacies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DataPrivacy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(dataprivaciesResource, c.ns, name, pt, data, subresources...), &v1alpha1.DataPrivacy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DataPrivacy), err
}
