/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-dynatrace-api/apis/autotag/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAutotags implements AutotagInterface
type FakeAutotags struct {
	Fake *FakeAutotagV1alpha1
	ns   string
}

var autotagsResource = schema.GroupVersionResource{Group: "autotag.dynatrace.kubeform.com", Version: "v1alpha1", Resource: "autotags"}

var autotagsKind = schema.GroupVersionKind{Group: "autotag.dynatrace.kubeform.com", Version: "v1alpha1", Kind: "Autotag"}

// Get takes name of the autotag, and returns the corresponding autotag object, and an error if there is any.
func (c *FakeAutotags) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Autotag, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(autotagsResource, c.ns, name), &v1alpha1.Autotag{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Autotag), err
}

// List takes label and field selectors, and returns the list of Autotags that match those selectors.
func (c *FakeAutotags) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AutotagList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(autotagsResource, autotagsKind, c.ns, opts), &v1alpha1.AutotagList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AutotagList{ListMeta: obj.(*v1alpha1.AutotagList).ListMeta}
	for _, item := range obj.(*v1alpha1.AutotagList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested autotags.
func (c *FakeAutotags) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(autotagsResource, c.ns, opts))

}

// Create takes the representation of a autotag and creates it.  Returns the server's representation of the autotag, and an error, if there is any.
func (c *FakeAutotags) Create(ctx context.Context, autotag *v1alpha1.Autotag, opts v1.CreateOptions) (result *v1alpha1.Autotag, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(autotagsResource, c.ns, autotag), &v1alpha1.Autotag{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Autotag), err
}

// Update takes the representation of a autotag and updates it. Returns the server's representation of the autotag, and an error, if there is any.
func (c *FakeAutotags) Update(ctx context.Context, autotag *v1alpha1.Autotag, opts v1.UpdateOptions) (result *v1alpha1.Autotag, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(autotagsResource, c.ns, autotag), &v1alpha1.Autotag{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Autotag), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAutotags) UpdateStatus(ctx context.Context, autotag *v1alpha1.Autotag, opts v1.UpdateOptions) (*v1alpha1.Autotag, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(autotagsResource, "status", c.ns, autotag), &v1alpha1.Autotag{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Autotag), err
}

// Delete takes name of the autotag and deletes it. Returns an error if one occurs.
func (c *FakeAutotags) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(autotagsResource, c.ns, name), &v1alpha1.Autotag{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAutotags) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(autotagsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.AutotagList{})
	return err
}

// Patch applies the patch and returns the patched autotag.
func (c *FakeAutotags) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Autotag, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(autotagsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Autotag{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Autotag), err
}
