/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-dynatrace-api/apis/key/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRequestses implements RequestsInterface
type FakeRequestses struct {
	Fake *FakeKeyV1alpha1
	ns   string
}

var requestsesResource = schema.GroupVersionResource{Group: "key.dynatrace.kubeform.com", Version: "v1alpha1", Resource: "requestses"}

var requestsesKind = schema.GroupVersionKind{Group: "key.dynatrace.kubeform.com", Version: "v1alpha1", Kind: "Requests"}

// Get takes name of the requests, and returns the corresponding requests object, and an error if there is any.
func (c *FakeRequestses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Requests, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(requestsesResource, c.ns, name), &v1alpha1.Requests{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Requests), err
}

// List takes label and field selectors, and returns the list of Requestses that match those selectors.
func (c *FakeRequestses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RequestsList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(requestsesResource, requestsesKind, c.ns, opts), &v1alpha1.RequestsList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RequestsList{ListMeta: obj.(*v1alpha1.RequestsList).ListMeta}
	for _, item := range obj.(*v1alpha1.RequestsList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested requestses.
func (c *FakeRequestses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(requestsesResource, c.ns, opts))

}

// Create takes the representation of a requests and creates it.  Returns the server's representation of the requests, and an error, if there is any.
func (c *FakeRequestses) Create(ctx context.Context, requests *v1alpha1.Requests, opts v1.CreateOptions) (result *v1alpha1.Requests, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(requestsesResource, c.ns, requests), &v1alpha1.Requests{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Requests), err
}

// Update takes the representation of a requests and updates it. Returns the server's representation of the requests, and an error, if there is any.
func (c *FakeRequestses) Update(ctx context.Context, requests *v1alpha1.Requests, opts v1.UpdateOptions) (result *v1alpha1.Requests, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(requestsesResource, c.ns, requests), &v1alpha1.Requests{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Requests), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRequestses) UpdateStatus(ctx context.Context, requests *v1alpha1.Requests, opts v1.UpdateOptions) (*v1alpha1.Requests, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(requestsesResource, "status", c.ns, requests), &v1alpha1.Requests{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Requests), err
}

// Delete takes name of the requests and deletes it. Returns an error if one occurs.
func (c *FakeRequestses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(requestsesResource, c.ns, name), &v1alpha1.Requests{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRequestses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(requestsesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.RequestsList{})
	return err
}

// Patch applies the patch and returns the patched requests.
func (c *FakeRequestses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Requests, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(requestsesResource, c.ns, name, pt, data, subresources...), &v1alpha1.Requests{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Requests), err
}
