/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-dynatrace-api/apis/resource/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAttributeses implements AttributesInterface
type FakeAttributeses struct {
	Fake *FakeResourceV1alpha1
	ns   string
}

var attributesesResource = schema.GroupVersionResource{Group: "resource.dynatrace.kubeform.com", Version: "v1alpha1", Resource: "attributeses"}

var attributesesKind = schema.GroupVersionKind{Group: "resource.dynatrace.kubeform.com", Version: "v1alpha1", Kind: "Attributes"}

// Get takes name of the attributes, and returns the corresponding attributes object, and an error if there is any.
func (c *FakeAttributeses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Attributes, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(attributesesResource, c.ns, name), &v1alpha1.Attributes{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Attributes), err
}

// List takes label and field selectors, and returns the list of Attributeses that match those selectors.
func (c *FakeAttributeses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AttributesList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(attributesesResource, attributesesKind, c.ns, opts), &v1alpha1.AttributesList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AttributesList{ListMeta: obj.(*v1alpha1.AttributesList).ListMeta}
	for _, item := range obj.(*v1alpha1.AttributesList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested attributeses.
func (c *FakeAttributeses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(attributesesResource, c.ns, opts))

}

// Create takes the representation of a attributes and creates it.  Returns the server's representation of the attributes, and an error, if there is any.
func (c *FakeAttributeses) Create(ctx context.Context, attributes *v1alpha1.Attributes, opts v1.CreateOptions) (result *v1alpha1.Attributes, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(attributesesResource, c.ns, attributes), &v1alpha1.Attributes{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Attributes), err
}

// Update takes the representation of a attributes and updates it. Returns the server's representation of the attributes, and an error, if there is any.
func (c *FakeAttributeses) Update(ctx context.Context, attributes *v1alpha1.Attributes, opts v1.UpdateOptions) (result *v1alpha1.Attributes, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(attributesesResource, c.ns, attributes), &v1alpha1.Attributes{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Attributes), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAttributeses) UpdateStatus(ctx context.Context, attributes *v1alpha1.Attributes, opts v1.UpdateOptions) (*v1alpha1.Attributes, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(attributesesResource, "status", c.ns, attributes), &v1alpha1.Attributes{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Attributes), err
}

// Delete takes name of the attributes and deletes it. Returns an error if one occurs.
func (c *FakeAttributeses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(attributesesResource, c.ns, name), &v1alpha1.Attributes{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAttributeses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(attributesesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.AttributesList{})
	return err
}

// Patch applies the patch and returns the patched attributes.
func (c *FakeAttributeses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Attributes, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(attributesesResource, c.ns, name, pt, data, subresources...), &v1alpha1.Attributes{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Attributes), err
}
