/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-dynatrace-api/apis/calculated/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeServiceMetrics implements ServiceMetricInterface
type FakeServiceMetrics struct {
	Fake *FakeCalculatedV1alpha1
	ns   string
}

var servicemetricsResource = schema.GroupVersionResource{Group: "calculated.dynatrace.kubeform.com", Version: "v1alpha1", Resource: "servicemetrics"}

var servicemetricsKind = schema.GroupVersionKind{Group: "calculated.dynatrace.kubeform.com", Version: "v1alpha1", Kind: "ServiceMetric"}

// Get takes name of the serviceMetric, and returns the corresponding serviceMetric object, and an error if there is any.
func (c *FakeServiceMetrics) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ServiceMetric, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(servicemetricsResource, c.ns, name), &v1alpha1.ServiceMetric{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServiceMetric), err
}

// List takes label and field selectors, and returns the list of ServiceMetrics that match those selectors.
func (c *FakeServiceMetrics) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ServiceMetricList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(servicemetricsResource, servicemetricsKind, c.ns, opts), &v1alpha1.ServiceMetricList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ServiceMetricList{ListMeta: obj.(*v1alpha1.ServiceMetricList).ListMeta}
	for _, item := range obj.(*v1alpha1.ServiceMetricList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested serviceMetrics.
func (c *FakeServiceMetrics) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(servicemetricsResource, c.ns, opts))

}

// Create takes the representation of a serviceMetric and creates it.  Returns the server's representation of the serviceMetric, and an error, if there is any.
func (c *FakeServiceMetrics) Create(ctx context.Context, serviceMetric *v1alpha1.ServiceMetric, opts v1.CreateOptions) (result *v1alpha1.ServiceMetric, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(servicemetricsResource, c.ns, serviceMetric), &v1alpha1.ServiceMetric{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServiceMetric), err
}

// Update takes the representation of a serviceMetric and updates it. Returns the server's representation of the serviceMetric, and an error, if there is any.
func (c *FakeServiceMetrics) Update(ctx context.Context, serviceMetric *v1alpha1.ServiceMetric, opts v1.UpdateOptions) (result *v1alpha1.ServiceMetric, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(servicemetricsResource, c.ns, serviceMetric), &v1alpha1.ServiceMetric{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServiceMetric), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeServiceMetrics) UpdateStatus(ctx context.Context, serviceMetric *v1alpha1.ServiceMetric, opts v1.UpdateOptions) (*v1alpha1.ServiceMetric, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(servicemetricsResource, "status", c.ns, serviceMetric), &v1alpha1.ServiceMetric{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServiceMetric), err
}

// Delete takes name of the serviceMetric and deletes it. Returns an error if one occurs.
func (c *FakeServiceMetrics) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(servicemetricsResource, c.ns, name), &v1alpha1.ServiceMetric{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeServiceMetrics) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(servicemetricsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ServiceMetricList{})
	return err
}

// Patch applies the patch and returns the patched serviceMetric.
func (c *FakeServiceMetrics) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ServiceMetric, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(servicemetricsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ServiceMetric{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServiceMetric), err
}
