/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-dynatrace-api/apis/span/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCaptureRules implements CaptureRuleInterface
type FakeCaptureRules struct {
	Fake *FakeSpanV1alpha1
	ns   string
}

var capturerulesResource = schema.GroupVersionResource{Group: "span.dynatrace.kubeform.com", Version: "v1alpha1", Resource: "capturerules"}

var capturerulesKind = schema.GroupVersionKind{Group: "span.dynatrace.kubeform.com", Version: "v1alpha1", Kind: "CaptureRule"}

// Get takes name of the captureRule, and returns the corresponding captureRule object, and an error if there is any.
func (c *FakeCaptureRules) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CaptureRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(capturerulesResource, c.ns, name), &v1alpha1.CaptureRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CaptureRule), err
}

// List takes label and field selectors, and returns the list of CaptureRules that match those selectors.
func (c *FakeCaptureRules) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CaptureRuleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(capturerulesResource, capturerulesKind, c.ns, opts), &v1alpha1.CaptureRuleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CaptureRuleList{ListMeta: obj.(*v1alpha1.CaptureRuleList).ListMeta}
	for _, item := range obj.(*v1alpha1.CaptureRuleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested captureRules.
func (c *FakeCaptureRules) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(capturerulesResource, c.ns, opts))

}

// Create takes the representation of a captureRule and creates it.  Returns the server's representation of the captureRule, and an error, if there is any.
func (c *FakeCaptureRules) Create(ctx context.Context, captureRule *v1alpha1.CaptureRule, opts v1.CreateOptions) (result *v1alpha1.CaptureRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(capturerulesResource, c.ns, captureRule), &v1alpha1.CaptureRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CaptureRule), err
}

// Update takes the representation of a captureRule and updates it. Returns the server's representation of the captureRule, and an error, if there is any.
func (c *FakeCaptureRules) Update(ctx context.Context, captureRule *v1alpha1.CaptureRule, opts v1.UpdateOptions) (result *v1alpha1.CaptureRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(capturerulesResource, c.ns, captureRule), &v1alpha1.CaptureRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CaptureRule), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCaptureRules) UpdateStatus(ctx context.Context, captureRule *v1alpha1.CaptureRule, opts v1.UpdateOptions) (*v1alpha1.CaptureRule, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(capturerulesResource, "status", c.ns, captureRule), &v1alpha1.CaptureRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CaptureRule), err
}

// Delete takes name of the captureRule and deletes it. Returns an error if one occurs.
func (c *FakeCaptureRules) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(capturerulesResource, c.ns, name), &v1alpha1.CaptureRule{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCaptureRules) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(capturerulesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.CaptureRuleList{})
	return err
}

// Patch applies the patch and returns the patched captureRule.
func (c *FakeCaptureRules) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CaptureRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(capturerulesResource, c.ns, name, pt, data, subresources...), &v1alpha1.CaptureRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CaptureRule), err
}
