apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: dynatrace.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: errorrules.application.dynatrace.kubeform.com
spec:
  group: application.dynatrace.kubeform.com
  names:
    kind: ErrorRules
    listKind: ErrorRulesList
    plural: errorrules
    singular: errorrules
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              backendRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  customErrors:
                    description: "An ordered list of HTTP errors. \n  Rules are evaluated
                      from top to bottom; the first matching rule applies"
                    properties:
                      rule:
                        description: Configuration of the custom error in the web
                          application
                        items:
                          properties:
                            capture:
                              description: Capture (`true`) or ignore (`false`) the
                                error
                              type: boolean
                            customAlerting:
                              description: Include (`true`) or exclude (`false`) the
                                error in Davis AI [problem detection and analysis](https://dt-url.net/a963kd2)
                              type: boolean
                            impactApdex:
                              description: Include (`true`) or exclude (`false`) the
                                error in Apdex calculation
                              type: boolean
                            keyMatcher:
                              description: The matching operation for the **keyPattern**.
                                Possible values are `BEGINS_WITH`, `CONTAINS`, `ENDS_WITH`
                                and `EQUALS`
                              type: string
                            keyPattern:
                              description: The key of the error to look for
                              type: string
                            valueMatcher:
                              description: The matching operation for the **valuePattern**.
                                Possible values are `BEGINS_WITH`, `CONTAINS`, `ENDS_WITH`
                                and `EQUALS`.
                              type: string
                            valuePattern:
                              description: The value of the error to look for
                              type: string
                          type: object
                        minItems: 1
                        type: array
                    required:
                    - rule
                    type: object
                  httpErrors:
                    description: "An ordered list of HTTP errors. \n  Rules are evaluated
                      from top to bottom; the first matching rule applies"
                    properties:
                      rule:
                        description: Configuration of the HTTP error in the web application
                        items:
                          properties:
                            capture:
                              description: Capture (`true`) or ignore (`false`) the
                                error
                              type: boolean
                            considerBlockedRequests:
                              description: If `true`, match by errors that have CSP
                                Rule violations
                              type: boolean
                            considerForAi:
                              description: Include (`true`) or exclude (`false`) the
                                error in Davis AI [problem detection and analysis](https://dt-url.net/a963kd2)
                              type: boolean
                            considerUnknownErrorCode:
                              description: If `true`, match by errors that have unknown
                                HTTP status code
                              type: boolean
                            errorCodes:
                              description: "The HTTP status code or status code range
                                to match by. \n This field is required if **considerUnknownErrorCode**
                                AND **considerBlockedRequests** are both set to `false`"
                              type: string
                            filter:
                              description: The matching rule for the URL. Popssible
                                values are `BEGINS_WITH`, `CONTAINS`, `ENDS_WITH`
                                and `EQUALS`.
                              type: string
                            filterByURL:
                              description: If `true`, filter errors by URL
                              type: boolean
                            impactApdex:
                              description: Include (`true`) or exclude (`false`) the
                                error in Apdex calculation
                              type: boolean
                            url:
                              description: The URL to look for
                              type: string
                          type: object
                        minItems: 1
                        type: array
                    required:
                    - rule
                    type: object
                  id:
                    type: string
                  ignoreCustomErrorsApdex:
                    description: Exclude (`true`) or include (`false`) custom errors
                      listed in **customErrorRules** in Apdex calculation
                    type: boolean
                  ignoreHTTPErrorsApdex:
                    description: Exclude (`true`) or include (`false`) HTTP errors
                      listed in **httpErrorRules** in Apdex calculation
                    type: boolean
                  ignoreJsErrorsApdex:
                    description: Exclude (`true`) or include (`false`) JavaScript
                      errors in Apdex calculation
                    type: boolean
                  webApplicationID:
                    description: The EntityID of the the WebApplication
                    type: string
                type: object
              state:
                properties:
                  customErrors:
                    description: "An ordered list of HTTP errors. \n  Rules are evaluated
                      from top to bottom; the first matching rule applies"
                    properties:
                      rule:
                        description: Configuration of the custom error in the web
                          application
                        items:
                          properties:
                            capture:
                              description: Capture (`true`) or ignore (`false`) the
                                error
                              type: boolean
                            customAlerting:
                              description: Include (`true`) or exclude (`false`) the
                                error in Davis AI [problem detection and analysis](https://dt-url.net/a963kd2)
                              type: boolean
                            impactApdex:
                              description: Include (`true`) or exclude (`false`) the
                                error in Apdex calculation
                              type: boolean
                            keyMatcher:
                              description: The matching operation for the **keyPattern**.
                                Possible values are `BEGINS_WITH`, `CONTAINS`, `ENDS_WITH`
                                and `EQUALS`
                              type: string
                            keyPattern:
                              description: The key of the error to look for
                              type: string
                            valueMatcher:
                              description: The matching operation for the **valuePattern**.
                                Possible values are `BEGINS_WITH`, `CONTAINS`, `ENDS_WITH`
                                and `EQUALS`.
                              type: string
                            valuePattern:
                              description: The value of the error to look for
                              type: string
                          type: object
                        minItems: 1
                        type: array
                    required:
                    - rule
                    type: object
                  httpErrors:
                    description: "An ordered list of HTTP errors. \n  Rules are evaluated
                      from top to bottom; the first matching rule applies"
                    properties:
                      rule:
                        description: Configuration of the HTTP error in the web application
                        items:
                          properties:
                            capture:
                              description: Capture (`true`) or ignore (`false`) the
                                error
                              type: boolean
                            considerBlockedRequests:
                              description: If `true`, match by errors that have CSP
                                Rule violations
                              type: boolean
                            considerForAi:
                              description: Include (`true`) or exclude (`false`) the
                                error in Davis AI [problem detection and analysis](https://dt-url.net/a963kd2)
                              type: boolean
                            considerUnknownErrorCode:
                              description: If `true`, match by errors that have unknown
                                HTTP status code
                              type: boolean
                            errorCodes:
                              description: "The HTTP status code or status code range
                                to match by. \n This field is required if **considerUnknownErrorCode**
                                AND **considerBlockedRequests** are both set to `false`"
                              type: string
                            filter:
                              description: The matching rule for the URL. Popssible
                                values are `BEGINS_WITH`, `CONTAINS`, `ENDS_WITH`
                                and `EQUALS`.
                              type: string
                            filterByURL:
                              description: If `true`, filter errors by URL
                              type: boolean
                            impactApdex:
                              description: Include (`true`) or exclude (`false`) the
                                error in Apdex calculation
                              type: boolean
                            url:
                              description: The URL to look for
                              type: string
                          type: object
                        minItems: 1
                        type: array
                    required:
                    - rule
                    type: object
                  id:
                    type: string
                  ignoreCustomErrorsApdex:
                    description: Exclude (`true`) or include (`false`) custom errors
                      listed in **customErrorRules** in Apdex calculation
                    type: boolean
                  ignoreHTTPErrorsApdex:
                    description: Exclude (`true`) or include (`false`) HTTP errors
                      listed in **httpErrorRules** in Apdex calculation
                    type: boolean
                  ignoreJsErrorsApdex:
                    description: Exclude (`true`) or include (`false`) JavaScript
                      errors in Apdex calculation
                    type: boolean
                  webApplicationID:
                    description: The EntityID of the the WebApplication
                    type: string
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
