apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: dynatrace.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: credentials.aws.dynatrace.kubeform.com
spec:
  group: aws.dynatrace.kubeform.com
  names:
    kind: Credentials
    listKind: CredentialsList
    plural: credentials
    singular: credentials
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              backendRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  authenticationData:
                    description: credentials for the AWS authentication
                    properties:
                      accessKey:
                        description: the access key
                        type: string
                      accountID:
                        description: the ID of the Amazon account
                        type: string
                      externalID:
                        description: the external ID token for setting an IAM role.
                          You can obtain it with the `GET /aws/iamExternalId` request
                        type: string
                      iamRole:
                        description: the IAM role to be used by Dynatrace to get monitoring
                          data
                        type: string
                      secretKey:
                        description: the secret access key
                        type: string
                      unknowns:
                        description: Any attributes that aren't yet supported by this
                          provider
                        type: string
                    type: object
                  id:
                    type: string
                  label:
                    description: The name of the credentials
                    type: string
                  partitionType:
                    description: The type of the AWS partition
                    type: string
                  supportingServicesToMonitor:
                    description: supporting services to be monitored
                    items:
                      properties:
                        monitoredMetrics:
                          description: a list of metrics to be monitored for this
                            service
                          items:
                            properties:
                              dimensions:
                                description: a list of metric's dimensions names
                                items:
                                  type: string
                                type: array
                              name:
                                description: the name of the metric of the supporting
                                  service
                                type: string
                              statistic:
                                description: 'the statistic (aggregation) to be used
                                  for the metric. AVG_MIN_MAX value is 3 statistics
                                  at once: AVERAGE, MINIMUM and MAXIMUM'
                                type: string
                              unknowns:
                                description: Any attributes that aren't yet supported
                                  by this provider
                                type: string
                            type: object
                          maxItems: 10
                          type: array
                        name:
                          description: the name of the supporting service
                          type: string
                        unknowns:
                          description: Any attributes that aren't yet supported by
                            this provider
                          type: string
                      type: object
                    maxItems: 10
                    type: array
                  taggedOnly:
                    description: Monitor only resources which have specified AWS tags
                      (`true`) or all resources (`false`)
                    type: boolean
                  tagsToMonitor:
                    description: AWS tags to be monitored. You can specify up to 10
                      tags. Only applicable when the **tagged_only** parameter is
                      set to `true`
                    items:
                      properties:
                        name:
                          description: the key of the AWS tag.
                          type: string
                        unknowns:
                          description: Any attributes that aren't yet supported by
                            this provider
                          type: string
                        value:
                          description: the value of the AWS tag
                          type: string
                      type: object
                    maxItems: 10
                    type: array
                  unknowns:
                    description: Any attributes that aren't yet supported by this
                      provider
                    type: string
                required:
                - authenticationData
                - partitionType
                - taggedOnly
                type: object
              state:
                properties:
                  authenticationData:
                    description: credentials for the AWS authentication
                    properties:
                      accessKey:
                        description: the access key
                        type: string
                      accountID:
                        description: the ID of the Amazon account
                        type: string
                      externalID:
                        description: the external ID token for setting an IAM role.
                          You can obtain it with the `GET /aws/iamExternalId` request
                        type: string
                      iamRole:
                        description: the IAM role to be used by Dynatrace to get monitoring
                          data
                        type: string
                      secretKey:
                        description: the secret access key
                        type: string
                      unknowns:
                        description: Any attributes that aren't yet supported by this
                          provider
                        type: string
                    type: object
                  id:
                    type: string
                  label:
                    description: The name of the credentials
                    type: string
                  partitionType:
                    description: The type of the AWS partition
                    type: string
                  supportingServicesToMonitor:
                    description: supporting services to be monitored
                    items:
                      properties:
                        monitoredMetrics:
                          description: a list of metrics to be monitored for this
                            service
                          items:
                            properties:
                              dimensions:
                                description: a list of metric's dimensions names
                                items:
                                  type: string
                                type: array
                              name:
                                description: the name of the metric of the supporting
                                  service
                                type: string
                              statistic:
                                description: 'the statistic (aggregation) to be used
                                  for the metric. AVG_MIN_MAX value is 3 statistics
                                  at once: AVERAGE, MINIMUM and MAXIMUM'
                                type: string
                              unknowns:
                                description: Any attributes that aren't yet supported
                                  by this provider
                                type: string
                            type: object
                          maxItems: 10
                          type: array
                        name:
                          description: the name of the supporting service
                          type: string
                        unknowns:
                          description: Any attributes that aren't yet supported by
                            this provider
                          type: string
                      type: object
                    maxItems: 10
                    type: array
                  taggedOnly:
                    description: Monitor only resources which have specified AWS tags
                      (`true`) or all resources (`false`)
                    type: boolean
                  tagsToMonitor:
                    description: AWS tags to be monitored. You can specify up to 10
                      tags. Only applicable when the **tagged_only** parameter is
                      set to `true`
                    items:
                      properties:
                        name:
                          description: the key of the AWS tag.
                          type: string
                        unknowns:
                          description: Any attributes that aren't yet supported by
                            this provider
                          type: string
                        value:
                          description: the value of the AWS tag
                          type: string
                      type: object
                    maxItems: 10
                    type: array
                  unknowns:
                    description: Any attributes that aren't yet supported by this
                      provider
                    type: string
                required:
                - authenticationData
                - partitionType
                - taggedOnly
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
