apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: dynatrace.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: credentials.azure.dynatrace.kubeform.com
spec:
  group: azure.dynatrace.kubeform.com
  names:
    kind: Credentials
    listKind: CredentialsList
    plural: credentials
    singular: credentials
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  active:
                    description: The monitoring is enabled (`true`) or disabled (`false`).  If
                      not set on creation, the `true` value is used.  If the field
                      is omitted during an update, the old value remains unaffected
                    type: boolean
                  appID:
                    description: The Application ID (also referred to as Client ID)  The
                      combination of Application ID and Directory ID must be unique
                    type: string
                  autoTagging:
                    description: The automatic capture of Azure tags is on (`true`)
                      or off (`false`)
                    type: boolean
                  directoryID:
                    description: The Directory ID (also referred to as Tenant ID)  The
                      combination of Application ID and Directory ID must be unique
                    type: string
                  id:
                    type: string
                  key:
                    description: ' The secret key associated with the Application
                      ID.  For security reasons, GET requests return this field as
                      `null`.   Submit your key on creation or update of the configuration.
                      If the field is omitted during an update, the old value remains
                      unaffected.'
                    type: string
                  label:
                    description: The unique name of the Azure credentials configuration.  Allowed
                      characters are letters, numbers, and spaces. Also the special
                      characters `.+-_` are allowed
                    type: string
                  monitorOnlyTagPairs:
                    description: A list of Azure tags to be monitored.  You can specify
                      up to 10 tags. A resource tagged with *any* of the specified
                      tags is monitored.  Only applicable when the **monitorOnlyTaggedEntities**
                      parameter is set to `true`
                    items:
                      properties:
                        name:
                          description: The name of the tag.
                          type: string
                        unknowns:
                          description: Any attributes that aren't yet supported by
                            this provider
                          type: string
                        value:
                          description: The value of the tag.   If set to `null`, then
                            resources with any value of the tag are monitored.
                          type: string
                      type: object
                    maxItems: 10
                    type: array
                  monitorOnlyTaggedEntities:
                    description: Monitor only resources that have specified Azure
                      tags (`true`) or all resources (`false`).
                    type: boolean
                  supportingServices:
                    description: A list of Azure supporting services to be monitored.
                      For each service there's a sublist of its metrics and the metrics'
                      dimensions that should be monitored. All of these elements (services,
                      metrics, dimensions) must have corresponding static definitions
                      on the server.
                    items:
                      properties:
                        monitoredMetrics:
                          description: A list of Azure tags to be monitored.  You
                            can specify up to 10 tags. A resource tagged with *any*
                            of the specified tags is monitored.  Only applicable when
                            the **monitorOnlyTaggedEntities** parameter is set to
                            `true`
                          items:
                            properties:
                              dimensions:
                                description: a list of metric's dimensions names
                                items:
                                  type: string
                                type: array
                              name:
                                description: the name of the metric of the supporting
                                  service
                                type: string
                              unknowns:
                                description: Any attributes that aren't yet supported
                                  by this provider
                                type: string
                            type: object
                          maxItems: 10
                          type: array
                        name:
                          description: The name of the supporting service.
                          type: string
                        unknowns:
                          description: Any attributes that aren't yet supported by
                            this provider
                          type: string
                      type: object
                    maxItems: 10
                    type: array
                  unknowns:
                    description: Any attributes that aren't yet supported by this
                      provider
                    type: string
                required:
                - active
                - monitorOnlyTaggedEntities
                type: object
              state:
                properties:
                  active:
                    description: The monitoring is enabled (`true`) or disabled (`false`).  If
                      not set on creation, the `true` value is used.  If the field
                      is omitted during an update, the old value remains unaffected
                    type: boolean
                  appID:
                    description: The Application ID (also referred to as Client ID)  The
                      combination of Application ID and Directory ID must be unique
                    type: string
                  autoTagging:
                    description: The automatic capture of Azure tags is on (`true`)
                      or off (`false`)
                    type: boolean
                  directoryID:
                    description: The Directory ID (also referred to as Tenant ID)  The
                      combination of Application ID and Directory ID must be unique
                    type: string
                  id:
                    type: string
                  key:
                    description: ' The secret key associated with the Application
                      ID.  For security reasons, GET requests return this field as
                      `null`.   Submit your key on creation or update of the configuration.
                      If the field is omitted during an update, the old value remains
                      unaffected.'
                    type: string
                  label:
                    description: The unique name of the Azure credentials configuration.  Allowed
                      characters are letters, numbers, and spaces. Also the special
                      characters `.+-_` are allowed
                    type: string
                  monitorOnlyTagPairs:
                    description: A list of Azure tags to be monitored.  You can specify
                      up to 10 tags. A resource tagged with *any* of the specified
                      tags is monitored.  Only applicable when the **monitorOnlyTaggedEntities**
                      parameter is set to `true`
                    items:
                      properties:
                        name:
                          description: The name of the tag.
                          type: string
                        unknowns:
                          description: Any attributes that aren't yet supported by
                            this provider
                          type: string
                        value:
                          description: The value of the tag.   If set to `null`, then
                            resources with any value of the tag are monitored.
                          type: string
                      type: object
                    maxItems: 10
                    type: array
                  monitorOnlyTaggedEntities:
                    description: Monitor only resources that have specified Azure
                      tags (`true`) or all resources (`false`).
                    type: boolean
                  supportingServices:
                    description: A list of Azure supporting services to be monitored.
                      For each service there's a sublist of its metrics and the metrics'
                      dimensions that should be monitored. All of these elements (services,
                      metrics, dimensions) must have corresponding static definitions
                      on the server.
                    items:
                      properties:
                        monitoredMetrics:
                          description: A list of Azure tags to be monitored.  You
                            can specify up to 10 tags. A resource tagged with *any*
                            of the specified tags is monitored.  Only applicable when
                            the **monitorOnlyTaggedEntities** parameter is set to
                            `true`
                          items:
                            properties:
                              dimensions:
                                description: a list of metric's dimensions names
                                items:
                                  type: string
                                type: array
                              name:
                                description: the name of the metric of the supporting
                                  service
                                type: string
                              unknowns:
                                description: Any attributes that aren't yet supported
                                  by this provider
                                type: string
                            type: object
                          maxItems: 10
                          type: array
                        name:
                          description: The name of the supporting service.
                          type: string
                        unknowns:
                          description: Any attributes that aren't yet supported by
                            this provider
                          type: string
                      type: object
                    maxItems: 10
                    type: array
                  unknowns:
                    description: Any attributes that aren't yet supported by this
                      provider
                    type: string
                required:
                - active
                - monitorOnlyTaggedEntities
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
