apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: dynatrace.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: services.custom.dynatrace.kubeform.com
spec:
  group: custom.dynatrace.kubeform.com
  names:
    kind: Service
    listKind: ServiceList
    plural: services
    singular: service
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  enabled:
                    description: Custom service enabled/disabled
                    type: boolean
                  id:
                    type: string
                  name:
                    description: The name of the custom service, displayed in the
                      UI
                    type: string
                  processGroups:
                    description: The list of process groups the custom service should
                      belong to
                    items:
                      type: string
                    type: array
                  queueEntryPoint:
                    description: The queue entry point flag. Set to `true` for custom
                      messaging services
                    type: boolean
                  queueEntryPointType:
                    description: The queue entry point type (IBM_MQ, JMS, KAFKA, MSMQ
                      or RABBIT_MQ)
                    type: string
                  rule:
                    description: The list of rules defining the custom service
                    items:
                      properties:
                        ID:
                          description: The ID of the detection rule
                          type: string
                        annotations:
                          description: Additional annotations filter of the rule.
                            Only classes where all listed annotations are available
                            in the class itself or any of its superclasses are instrumented.
                            Not applicable to PHP
                          items:
                            type: string
                          type: array
                        class:
                          description: The fully qualified class or interface to instrument
                            (or a substring if matching to a string). Required for
                            Java and .NET custom services. Not applicable to PHP
                          properties:
                            match:
                              description: Matcher applying to the class name (ENDS_WITH,
                                EQUALS or STARTS_WITH). STARTS_WITH can only be used
                                if there is at least one annotation defined. Default
                                value is EQUALS
                              type: string
                            name:
                              description: The full name of the class / the name to
                                match the class name with
                              type: string
                          required:
                          - name
                          type: object
                        enabled:
                          description: Rule enabled/disabled
                          type: boolean
                        file:
                          description: The PHP file containing the class or methods
                            to instrument. Required for PHP custom service. Not applicable
                            to Java and .NET
                          properties:
                            match:
                              description: Matcher applying to the file name (ENDS_WITH,
                                EQUALS or STARTS_WITH). Default value is ENDS_WITH
                                (if applicable)
                              type: string
                            name:
                              description: The full name of the file / the name to
                                match the file name with
                              type: string
                          required:
                          - name
                          type: object
                        method:
                          description: methods to instrument
                          items:
                            properties:
                              ID:
                                description: The ID of the method rule
                                type: string
                              arguments:
                                description: Fully qualified types of argument the
                                  method expects
                                items:
                                  type: string
                                type: array
                              name:
                                description: The method to instrument
                                type: string
                              returns:
                                description: Fully qualified type the method returns
                                type: string
                              unknowns:
                                description: allows for configuring properties that
                                  are not explicitly supported by the current version
                                  of this provider
                                type: string
                            required:
                            - name
                            type: object
                          type: array
                        unknowns:
                          description: allows for configuring properties that are
                            not explicitly supported by the current version of this
                            provider
                          type: string
                      required:
                      - enabled
                      - method
                      type: object
                    type: array
                  technology:
                    description: Matcher applying to the file name (ENDS_WITH, EQUALS
                      or STARTS_WITH). Default value is ENDS_WITH (if applicable)
                    type: string
                  unknowns:
                    description: allows for configuring properties that are not explicitly
                      supported by the current version of this provider
                    type: string
                required:
                - enabled
                - name
                - technology
                type: object
              state:
                properties:
                  enabled:
                    description: Custom service enabled/disabled
                    type: boolean
                  id:
                    type: string
                  name:
                    description: The name of the custom service, displayed in the
                      UI
                    type: string
                  processGroups:
                    description: The list of process groups the custom service should
                      belong to
                    items:
                      type: string
                    type: array
                  queueEntryPoint:
                    description: The queue entry point flag. Set to `true` for custom
                      messaging services
                    type: boolean
                  queueEntryPointType:
                    description: The queue entry point type (IBM_MQ, JMS, KAFKA, MSMQ
                      or RABBIT_MQ)
                    type: string
                  rule:
                    description: The list of rules defining the custom service
                    items:
                      properties:
                        ID:
                          description: The ID of the detection rule
                          type: string
                        annotations:
                          description: Additional annotations filter of the rule.
                            Only classes where all listed annotations are available
                            in the class itself or any of its superclasses are instrumented.
                            Not applicable to PHP
                          items:
                            type: string
                          type: array
                        class:
                          description: The fully qualified class or interface to instrument
                            (or a substring if matching to a string). Required for
                            Java and .NET custom services. Not applicable to PHP
                          properties:
                            match:
                              description: Matcher applying to the class name (ENDS_WITH,
                                EQUALS or STARTS_WITH). STARTS_WITH can only be used
                                if there is at least one annotation defined. Default
                                value is EQUALS
                              type: string
                            name:
                              description: The full name of the class / the name to
                                match the class name with
                              type: string
                          required:
                          - name
                          type: object
                        enabled:
                          description: Rule enabled/disabled
                          type: boolean
                        file:
                          description: The PHP file containing the class or methods
                            to instrument. Required for PHP custom service. Not applicable
                            to Java and .NET
                          properties:
                            match:
                              description: Matcher applying to the file name (ENDS_WITH,
                                EQUALS or STARTS_WITH). Default value is ENDS_WITH
                                (if applicable)
                              type: string
                            name:
                              description: The full name of the file / the name to
                                match the file name with
                              type: string
                          required:
                          - name
                          type: object
                        method:
                          description: methods to instrument
                          items:
                            properties:
                              ID:
                                description: The ID of the method rule
                                type: string
                              arguments:
                                description: Fully qualified types of argument the
                                  method expects
                                items:
                                  type: string
                                type: array
                              name:
                                description: The method to instrument
                                type: string
                              returns:
                                description: Fully qualified type the method returns
                                type: string
                              unknowns:
                                description: allows for configuring properties that
                                  are not explicitly supported by the current version
                                  of this provider
                                type: string
                            required:
                            - name
                            type: object
                          type: array
                        unknowns:
                          description: allows for configuring properties that are
                            not explicitly supported by the current version of this
                            provider
                          type: string
                      required:
                      - enabled
                      - method
                      type: object
                    type: array
                  technology:
                    description: Matcher applying to the file name (ENDS_WITH, EQUALS
                      or STARTS_WITH). Default value is ENDS_WITH (if applicable)
                    type: string
                  unknowns:
                    description: allows for configuring properties that are not explicitly
                      supported by the current version of this provider
                    type: string
                required:
                - enabled
                - name
                - technology
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
