apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: dynatrace.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: credentials.k8s.dynatrace.kubeform.com
spec:
  group: k8s.dynatrace.kubeform.com
  names:
    kind: Credentials
    listKind: CredentialsList
    plural: credentials
    singular: credentials
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              backendRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  active:
                    description: Monitoring is enabled (`true`) or disabled (`false`)
                      for given credentials configuration.  If not set on creation,
                      the `true` value is used.  If the field is omitted during an
                      update, the old value remains unaffected.
                    type: boolean
                  authToken:
                    description: The service account bearer token for the Kubernetes
                      API server.  Submit your token on creation or update of the
                      configuration. For security reasons, GET requests return this
                      field as `null`.  If the field is omitted during an update,
                      the old value remains unaffected.
                    type: string
                  certificateCheckEnabled:
                    description: The check of SSL certificates is enabled (`true`)
                      or disabled (`false`) for the Kubernetes cluster.  If not set
                      on creation, the `true` value is used.  If the field is omitted
                      during an update, the old value remains unaffected.
                    type: boolean
                  davisEventsIntegrationEnabled:
                    description: Inclusion of all Davis relevant events is enabled
                      (`true`) or disabled (`false`) for the Kubernetes cluster. If
                      the field is omitted during an update, the old value remains
                      unaffected
                    type: boolean
                  endpointURL:
                    description: The URL of the Kubernetes API server.  It must be
                      unique within a Dynatrace environment.  The URL must valid according
                      to RFC 2396. Leading or trailing whitespaces are not allowed.
                    type: string
                  eventAnalysisAndAlertingEnabled:
                    description: Event analysis and alerting is (`true`) or disabled
                      (`false`) for the Kubernetes cluster. If the field is omitted
                      during an update, the old value remains unaffected.
                    type: boolean
                  eventsFieldSelectors:
                    description: The check of SSL certificates is enabled (`true`)
                      or disabled (`false`) for the Kubernetes cluster.  If not set
                      on creation, the `true` value is used.  If the field is omitted
                      during an update, the old value remains unaffected.
                    items:
                      properties:
                        active:
                          description: Whether subscription to this events field selector
                            is enabled (value set to `true`). If disabled (value set
                            to `false`), Dynatrace will stop fetching events from
                            the Kubernetes API for this events field selector
                          type: boolean
                        fieldSelector:
                          description: The field selector string (url decoding is
                            applied) when storing it.
                          type: string
                        label:
                          description: A label of the events field selector.
                          type: string
                        unknowns:
                          description: Any attributes that aren't yet supported by
                            this provider
                          type: string
                      required:
                      - active
                      - fieldSelector
                      - label
                      type: object
                    type: array
                  eventsIntegrationEnabled:
                    description: Monitoring of events is enabled (`true`) or disabled
                      (`false`) for the Kubernetes cluster. Event monitoring depends
                      on the active state of this configuration to be true.  If not
                      set on creation, the `false` value is used.  If the field is
                      omitted during an update, the old value remains unaffected.
                    type: boolean
                  hostnameVerification:
                    description: Verify hostname in certificate against Kubernetes
                      API URL
                    type: boolean
                  id:
                    type: string
                  label:
                    description: 'The name of the Kubernetes credentials configuration.  Allowed
                      characters are letters, numbers, whitespaces, and the following
                      characters: `.+-_`. Leading or trailing whitespace is not allowed.'
                    type: string
                  prometheusExporters:
                    description: Prometheus exporters integration is enabled (`true`)
                      or disabled (`false`) for the Kubernetes cluster.If the field
                      is omitted during an update, the old value remains unaffected
                    type: boolean
                  unknowns:
                    description: Any attributes that aren't yet supported by this
                      provider
                    type: string
                  workloadIntegrationEnabled:
                    description: Workload and cloud application processing is enabled
                      (`true`) or disabled (`false`) for the Kubernetes cluster. If
                      the field is omitted during an update, the old value remains
                      unaffected.
                    type: boolean
                required:
                - label
                type: object
              state:
                properties:
                  active:
                    description: Monitoring is enabled (`true`) or disabled (`false`)
                      for given credentials configuration.  If not set on creation,
                      the `true` value is used.  If the field is omitted during an
                      update, the old value remains unaffected.
                    type: boolean
                  authToken:
                    description: The service account bearer token for the Kubernetes
                      API server.  Submit your token on creation or update of the
                      configuration. For security reasons, GET requests return this
                      field as `null`.  If the field is omitted during an update,
                      the old value remains unaffected.
                    type: string
                  certificateCheckEnabled:
                    description: The check of SSL certificates is enabled (`true`)
                      or disabled (`false`) for the Kubernetes cluster.  If not set
                      on creation, the `true` value is used.  If the field is omitted
                      during an update, the old value remains unaffected.
                    type: boolean
                  davisEventsIntegrationEnabled:
                    description: Inclusion of all Davis relevant events is enabled
                      (`true`) or disabled (`false`) for the Kubernetes cluster. If
                      the field is omitted during an update, the old value remains
                      unaffected
                    type: boolean
                  endpointURL:
                    description: The URL of the Kubernetes API server.  It must be
                      unique within a Dynatrace environment.  The URL must valid according
                      to RFC 2396. Leading or trailing whitespaces are not allowed.
                    type: string
                  eventAnalysisAndAlertingEnabled:
                    description: Event analysis and alerting is (`true`) or disabled
                      (`false`) for the Kubernetes cluster. If the field is omitted
                      during an update, the old value remains unaffected.
                    type: boolean
                  eventsFieldSelectors:
                    description: The check of SSL certificates is enabled (`true`)
                      or disabled (`false`) for the Kubernetes cluster.  If not set
                      on creation, the `true` value is used.  If the field is omitted
                      during an update, the old value remains unaffected.
                    items:
                      properties:
                        active:
                          description: Whether subscription to this events field selector
                            is enabled (value set to `true`). If disabled (value set
                            to `false`), Dynatrace will stop fetching events from
                            the Kubernetes API for this events field selector
                          type: boolean
                        fieldSelector:
                          description: The field selector string (url decoding is
                            applied) when storing it.
                          type: string
                        label:
                          description: A label of the events field selector.
                          type: string
                        unknowns:
                          description: Any attributes that aren't yet supported by
                            this provider
                          type: string
                      required:
                      - active
                      - fieldSelector
                      - label
                      type: object
                    type: array
                  eventsIntegrationEnabled:
                    description: Monitoring of events is enabled (`true`) or disabled
                      (`false`) for the Kubernetes cluster. Event monitoring depends
                      on the active state of this configuration to be true.  If not
                      set on creation, the `false` value is used.  If the field is
                      omitted during an update, the old value remains unaffected.
                    type: boolean
                  hostnameVerification:
                    description: Verify hostname in certificate against Kubernetes
                      API URL
                    type: boolean
                  id:
                    type: string
                  label:
                    description: 'The name of the Kubernetes credentials configuration.  Allowed
                      characters are letters, numbers, whitespaces, and the following
                      characters: `.+-_`. Leading or trailing whitespace is not allowed.'
                    type: string
                  prometheusExporters:
                    description: Prometheus exporters integration is enabled (`true`)
                      or disabled (`false`) for the Kubernetes cluster.If the field
                      is omitted during an update, the old value remains unaffected
                    type: boolean
                  unknowns:
                    description: Any attributes that aren't yet supported by this
                      provider
                    type: string
                  workloadIntegrationEnabled:
                    description: Workload and cloud application processing is enabled
                      (`true`) or disabled (`false`) for the Kubernetes cluster. If
                      the field is omitted during an update, the old value remains
                      unaffected.
                    type: boolean
                required:
                - label
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
