apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: dynatrace.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: groups.user.dynatrace.kubeform.com
spec:
  group: user.dynatrace.kubeform.com
  names:
    kind: Group
    listKind: GroupList
    plural: groups
    singular: group
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              backendRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  accessAccount:
                    description: If `true`, then the group has the access account
                      rights
                    type: boolean
                  clusterAdmin:
                    description: If `true`, then the group has the cluster administrator
                      rights
                    type: boolean
                  id:
                    type: string
                  ldapGroups:
                    description: LDAP group names
                    items:
                      type: string
                    type: array
                  manageAccount:
                    description: If `true`, then the group has the manage account
                      rights
                    type: boolean
                  name:
                    description: The name of the user group
                    type: string
                  permissions:
                    description: Permissions for environments
                    properties:
                      grant:
                        description: A permission granted to one or multiple environments
                        items:
                          properties:
                            environments:
                              description: The ids of the environments this permission
                                grants the user access to.
                              items:
                                type: string
                              type: array
                            permission:
                              description: The permission. Possible values are `VIEWER`,
                                `MANAGE_SETTINGS`, `AGENT_INSTALL`, `LOG_VIEWER`,
                                `VIEW_SENSITIVE_REQUEST_DATA`, `CONFIGURE_REQUEST_CAPTURE_DATA`,
                                `REPLAY_SESSION_DATA`, `REPLAY_SESSION_DATA_WITHOUT_MASKING`,
                                `MANAGE_SECURITY_PROBLEMS` and `MANAGE_SUPPORT_TICKETS`.
                              type: string
                          required:
                          - permission
                          type: object
                        minItems: 1
                        type: array
                    required:
                    - grant
                    type: object
                  ssoGroups:
                    description: SSO group names. If defined it's used to map SSO
                      group name to Dynatrace group name, otherwise mapping is done
                      by group name
                    items:
                      type: string
                    type: array
                required:
                - name
                type: object
              state:
                properties:
                  accessAccount:
                    description: If `true`, then the group has the access account
                      rights
                    type: boolean
                  clusterAdmin:
                    description: If `true`, then the group has the cluster administrator
                      rights
                    type: boolean
                  id:
                    type: string
                  ldapGroups:
                    description: LDAP group names
                    items:
                      type: string
                    type: array
                  manageAccount:
                    description: If `true`, then the group has the manage account
                      rights
                    type: boolean
                  name:
                    description: The name of the user group
                    type: string
                  permissions:
                    description: Permissions for environments
                    properties:
                      grant:
                        description: A permission granted to one or multiple environments
                        items:
                          properties:
                            environments:
                              description: The ids of the environments this permission
                                grants the user access to.
                              items:
                                type: string
                              type: array
                            permission:
                              description: The permission. Possible values are `VIEWER`,
                                `MANAGE_SETTINGS`, `AGENT_INSTALL`, `LOG_VIEWER`,
                                `VIEW_SENSITIVE_REQUEST_DATA`, `CONFIGURE_REQUEST_CAPTURE_DATA`,
                                `REPLAY_SESSION_DATA`, `REPLAY_SESSION_DATA_WITHOUT_MASKING`,
                                `MANAGE_SECURITY_PROBLEMS` and `MANAGE_SUPPORT_TICKETS`.
                              type: string
                          required:
                          - permission
                          type: object
                        minItems: 1
                        type: array
                    required:
                    - grant
                    type: object
                  ssoGroups:
                    description: SSO group names. If defined it's used to map SSO
                      group name to Dynatrace group name, otherwise mapping is done
                      by group name
                    items:
                      type: string
                    type: array
                required:
                - name
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
