/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "kubeform.dev/provider-dynatrace-api/apis/resource/v1alpha1"
	scheme "kubeform.dev/provider-dynatrace-api/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AttributesesGetter has a method to return a AttributesInterface.
// A group's client should implement this interface.
type AttributesesGetter interface {
	Attributeses(namespace string) AttributesInterface
}

// AttributesInterface has methods to work with Attributes resources.
type AttributesInterface interface {
	Create(ctx context.Context, attributes *v1alpha1.Attributes, opts v1.CreateOptions) (*v1alpha1.Attributes, error)
	Update(ctx context.Context, attributes *v1alpha1.Attributes, opts v1.UpdateOptions) (*v1alpha1.Attributes, error)
	UpdateStatus(ctx context.Context, attributes *v1alpha1.Attributes, opts v1.UpdateOptions) (*v1alpha1.Attributes, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Attributes, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.AttributesList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Attributes, err error)
	AttributesExpansion
}

// attributeses implements AttributesInterface
type attributeses struct {
	client rest.Interface
	ns     string
}

// newAttributeses returns a Attributeses
func newAttributeses(c *ResourceV1alpha1Client, namespace string) *attributeses {
	return &attributeses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the attributes, and returns the corresponding attributes object, and an error if there is any.
func (c *attributeses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Attributes, err error) {
	result = &v1alpha1.Attributes{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("attributeses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Attributeses that match those selectors.
func (c *attributeses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AttributesList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.AttributesList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("attributeses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested attributeses.
func (c *attributeses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("attributeses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a attributes and creates it.  Returns the server's representation of the attributes, and an error, if there is any.
func (c *attributeses) Create(ctx context.Context, attributes *v1alpha1.Attributes, opts v1.CreateOptions) (result *v1alpha1.Attributes, err error) {
	result = &v1alpha1.Attributes{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("attributeses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(attributes).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a attributes and updates it. Returns the server's representation of the attributes, and an error, if there is any.
func (c *attributeses) Update(ctx context.Context, attributes *v1alpha1.Attributes, opts v1.UpdateOptions) (result *v1alpha1.Attributes, err error) {
	result = &v1alpha1.Attributes{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("attributeses").
		Name(attributes.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(attributes).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *attributeses) UpdateStatus(ctx context.Context, attributes *v1alpha1.Attributes, opts v1.UpdateOptions) (result *v1alpha1.Attributes, err error) {
	result = &v1alpha1.Attributes{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("attributeses").
		Name(attributes.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(attributes).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the attributes and deletes it. Returns an error if one occurs.
func (c *attributeses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("attributeses").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *attributeses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("attributeses").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched attributes.
func (c *attributeses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Attributes, err error) {
	result = &v1alpha1.Attributes{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("attributeses").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
